### ISSUE TITLE
not installable because META.info no longer supported by zef 

### ISSUE THREAD

**Issue by masukomi** [dagurval/p6-Time-Duration#11]
[see this comment](https://github.com/ugexe/zef/issues/492#issuecomment-1387184611) 

META.info needs to be renamed META.json

**Comment by ugexe** [comment]
see this 5 year old PR: https://github.com/dagurval/p6-Time-Duration/pull/6

**Comment by masukomi** [comment]
closing. should be all good now with the latest release.
